### ISSUE TITLE
Log rotation/retention !!

### ISSUE THREAD

**Issue by Dibya19** [pingidentity/pingidentity-cdr-sandbox#57]
Hi ,
The way we manage the log rotation and cleanup by modifying the log4j2.xml file in Ping federate and Ping access. 
Similarly do we have any configuration file for Ping data console adjustments to achieve the Ping data console log rotation and cleanup.
If yes, Can you please provide the exact path to the file and the file name along with documentation.

**Comment by andrewclatham** [comment]
@Dibya19 - Unless you have a specific need to administer the Directory via the Web-based console I would recommend disabling that container from starting up by commenting out the pingdataconsole section in docker-compose.yaml. This directory GUI console was included for demonstration purposes only with most configuration performed by the command-line and LDIF files.

For the rest of the product logging:
PingDirectory - https://docs.pingidentity.com/bundle/pingdirectory-82/page/iqu1603919613584.html
PingDataGov - https://docs.pingidentity.com/bundle/pingdatagovernance-82/page/goo1564011508461.html
